"""Initial schema

Revision ID: 8c814be0766b
Revises: 
Create Date: 2026-01-29 10:51:18.986471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c814be0766b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=False),
    sa.Column('computer_name', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('specs', sa.Text(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.Column('refresh_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_name', sa.String(length=200), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('cost_center', sa.String(length=50), nullable=True),
    sa.Column('location_building', sa.String(length=100), nullable=True),
    sa.Column('location_floor', sa.String(length=50), nullable=True),
    sa.Column('location_room', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_tag', 'assets', ['asset_tag'], unique=False)
    op.create_index('idx_assigned_user_id', 'assets', ['assigned_user_id'], unique=False)
    op.create_index('idx_department', 'assets', ['department'], unique=False)
    op.create_index('idx_refresh_due_date', 'assets', ['refresh_due_date'], unique=False)
    op.create_index('idx_status', 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_asset_tag'), 'assets', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_assets_assigned_user_id'), 'assets', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_assets_department'), 'assets', ['department'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_refresh_due_date'), 'assets', ['refresh_due_date'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('column_mapping', sa.Text(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_id'), 'imports', ['id'], unique=False)
    op.create_table('verification_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verified_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_campaigns_id'), 'verification_campaigns', ['id'], unique=False)
    op.create_table('asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_history_id'), 'asset_history', ['id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verified_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['verification_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_id'), 'verification_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_asset_history_id'), table_name='asset_history')
    op.drop_table('asset_history')
    op.drop_index(op.f('ix_verification_campaigns_id'), table_name='verification_campaigns')
    op.drop_table('verification_campaigns')
    op.drop_index(op.f('ix_imports_id'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_refresh_due_date'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_department'), table_name='assets')
    op.drop_index(op.f('ix_assets_assigned_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_tag'), table_name='assets')
    op.drop_index('idx_status', table_name='assets')
    op.drop_index('idx_refresh_due_date', table_name='assets')
    op.drop_index('idx_department', table_name='assets')
    op.drop_index('idx_assigned_user_id', table_name='assets')
    op.drop_index('idx_asset_tag', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
